### ISSUE TITLE
`SearchBar` - provide value when `onSubmit` is called

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#670] opened 2022-09-05 11:19 UTC

**Comment by dzonidoo** [comment] 2022-09-09 12:20
https://github.com/superdesk/superdesk-ui-framework/pull/674
I also added enter key functionality to trigger onSubmit...

**Comment by tomaskikutis** [comment] 2022-09-10 11:33
Only close issues when work is finished - if there's an open PR, it's not finished yet

**Comment by pavlovicnemanja** [comment] 2022-09-15 08:07
@tomaskikutis can you test and close the issue? tnx

**Comment by tomaskikutis** [comment] 2022-09-15 08:36
I think it's an overkill for me to test every single tiny change. If you fully understand the issue, feel free to merge it and close GitHub issue without my me.

**Comment by pavlovicnemanja** [comment] 2022-09-15 08:43
I agree, but previous agreement was not to close issue until you confirmed it.

**Comment by tomaskikutis** [comment] 2022-09-15 08:51
Maybe it was a misunderstanding. If I don't tell in advance that I want to test a certain thing, merge it without me. I sometimes want to check some complex new components like tree select, but that's an exception, not the rule.

**Comment by pavlovicnemanja** [comment] 2022-09-15 08:52
works for me! :)

**Comment by pavlovicnemanja** [comment] 2022-09-15 10:49
Tested and confirmed

**Closed as completed by pavlovicnemanja** 2022-09-15 10:49 UTC
Labels: broadcasting, Testing
